contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #variantbenchmarking channel"
    url: https://nfcore.slack.com/channels/variantbenchmarking
    about: Discussion about the nf-core/variantbenchmarking pipeline
